---
name: tests

on: [push, pull_request]

jobs:
  lts:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: msimerson/node-lts-versions@v1.1.1
  test:
    runs-on: ${{ matrix.os }}
    needs: lts

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: msimerson/node-lts-versions@v1.1.1

        with:
          node-version: ${{ needs.lts.outputs.lts }}
      - run: echo ${{ needs.lts.outputs.lts }}
      - run: npm i
      - run: npm test
